version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/newman-reporter-testomatio
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/testcafe
    schedule:
      interval: monthly
